import './globals.css';

import { geistMono, geistSans } from '@/lib/fonts';

import type { Metadata } from 'next';
import { Providers } from '@/components/provider';
import { cn } from '@/lib/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'font-geistSans antialiased',
          geistSans.variable,
          geistMono.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
