import "./globals.css";

import { geistMono, geistSans } from "@/lib/fonts";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-geistSans`}
      >
        {children}
      </body>
    </html>
  );
}
